version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.dineug.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.dineug.com'
    ports:
      - 80:80
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./backups:/var/opt/gitlab/backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
