version: '3.7'
services:
  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=sentry
    volumes:
      - ./postgres:/var/lib/postgresql/data

  sentry:
    image: sentry:latest
    restart: always
    links:
      - redis
      - postgres
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SENTRY_SECRET_KEY=###secret-key###
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry

  cron:
    image: sentry:latest
    restart: always
    command: "run cron"
    links:
      - redis
      - postgres
    environment:
      - SENTRY_SECRET_KEY=###secret-key###
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry

  worker:
    image: sentry:latest
    restart: always
    command: "run worker"
    links:
      - redis
      - postgres
    environment:
      - SENTRY_SECRET_KEY=###secret-key###
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry
